kind: Deployment
apiVersion: apps/v1
metadata:
  name: t3.backend.deployment
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mendhak/http-https-echo
          ports:
            - containerPort: 80
    
